config/routes.rb
Rails.application.routes.draw do

  get "home/index"

  resources :snowboards

  root "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @home_url = request.base_url
  end

end

app/controllers/snowboards_controller.rb
class SnowboardsController < ApplicationController

  def new

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<!-- Home Navbar -->
<div class="home_navbar">
  <div class="home_navbar_logo">
    <a href="javascript:history.go(0)">White Glade</a>
  </div>
  <div id="genders" class="genders">
    <div class="mars_stroke">
      <i class="fas fa-mars fa-lg"></i>
    </div>
    <div class="venus_stroke">
      <i class="fas fa-venus fa-lg"></i>
    </div>
  </div>
</div>

<!-- Home Banner -->
<div class="home_banner">
  <div class="home_title"><h1>White Glade</h1></div>
  <div class="home_text"><p>For powder enthusiasts ❄️ 🤟</p></div>
</div>

<!-- Home Carousel -->

<div id="carousel_shell">

  <div id="carousel_left_arrow"></div>

  <div id="carousel_container">

    <div class="item">
      <div class="item_image">
        <img src="assets/carousel/nike-sb-logo.png">
      </div>
    </div>

    <div class="item">
      <div class="item_image">
        <img src="assets/carousel/burton-logo.png">
      </div>
    </div>

    <div class="item">
      <div class="item_image">
        <img src="assets/carousel/new-balance-logo.png">
      </div>
    </div>

    <div class="item">
      <div class="item_image">
        <img src="assets/carousel/billabong-logo.png">
      </div>
    </div>

    <div class="item">
      <div class="item_image">
        <img src="assets/carousel/new-era-logo.png">
      </div>
    </div>

    <div class="item">
      <div class="item_image">
        <img src="assets/carousel/bench-logo.png">
      </div>
    </div>

    <div class="item">
      <div class="item_image">
        <img src="assets/carousel/nike-sb-logo.png">
      </div>
    </div>

    <div class="item">
      <div class="item_image">
        <img src="assets/carousel/burton-logo.png">
      </div>
    </div>

    <div class="item">
      <div class="item_image">
        <img src="assets/carousel/new-balance-logo.png">
      </div>
    </div>

    <div class="item">
      <div class="item_image">
        <img src="assets/carousel/billabong-logo.png">
      </div>
    </div>

    <div class="item">
      <div class="item_image">
        <img src="assets/carousel/new-era-logo.png">
      </div>
    </div>

    <div class="item">
      <div class="item_image">
        <img src="assets/carousel/bench-logo.png">
      </div>
    </div>

  </div>

  <div id="carousel_right_arrow"></div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhiteGlade</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">

    <!-- FontAwesome -->
    <script src="https://kit.fontawesome.com/fafd11bfb7.js" crossorigin="anonymous"></script>

    <!-- Global styles -->
    <style>
      body {
        margin: 0;
        font-family: 'Roboto', sans-serif;
      }
      p {
        margin: 0;
      }
      a {
        text-decoration: none;
      }
      a:hover {
        text-decoration: none;
      }
    </style>
  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/snowboards/new.html.erb
<h1>Snowboards</h1>

<%= form_with scope: :snowboard, url: snowboards_path do |form| %>

  <p><%= form.label :name %> <%= form.text_field :name%></p><br>

  <p><%= form.submit %></p>

<% end %>